name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - cupy
  - jax[cuda]
  - scipy
  - pre-commit==3.7.1
  - black==24.4.2
  - flake8==7.1.0
  - parameterized==0.9.0
  - pytest==8.2.2
  - pytest-rerunfailures==14.0
  - pyyaml==6.0.1
  - conda-libmamba-solver
  - libmamba
  - libmambapy
  - libarchive
