"""Optional shape-aware static view of the runtime NewType layout brands."""

from typing import Generic, TypeGuard, TypeVar, Union, overload

from shape_extensions import IntTuple, broadcast
from torch import Tensor
from typing_extensions import Self

_Shape = TypeVar("_Shape", bound=IntTuple)

class _SparseTensor(Tensor[_Shape], Generic[_Shape]):
    # Like NewType at runtime, this constructor does not validate the layout.
    def __new__(cls, value: Tensor[_Shape]) -> Self: ...
    def clone(self, *, memory_format: object = ...) -> Self: ...
    def detach(self) -> Self: ...
    def to_dense(self, dtype: object = ..., *, masked_grad: bool = ...) -> Tensor[_Shape]: ...
    def to_sparse_coo(self) -> SparseCOOTensor[_Shape]: ...
    def to_sparse_csr(self, dense_dim: int | None = ...) -> SparseCSRTensor[_Shape]: ...
    def to_sparse_csc(self, dense_dim: int | None = ...) -> SparseCSCTensor[_Shape]: ...
    # Upstream annotates T as Self, which wrongly preserves compressed layout
    # and shape on transpose. Conservatively discard the layout and shape.
    @property
    def T(self) -> Tensor: ...  # pyrefly: ignore [bad-override]

    # Upstream Self return types are unsound for broadcasting. Tensor operands
    # produce an unbranded Tensor with the broadcast shape; validate its layout
    # before a sparse consumer. Each ignore replaces that incorrect Self type.
    def add[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other], *, alpha: int | float = ...
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def sub[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other], *, alpha: int | float = ...
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    @overload
    def mul[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    @overload
    def mul(self, other: int | float) -> Self: ...
    @overload
    def div[Other: IntTuple](
        self, other: Tensor[Other], *, rounding_mode: str | None = ...
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    @overload
    def div(self, other: int | float, *, rounding_mode: str | None = ...) -> Self: ...
    @overload
    def pow[Other: IntTuple](self, exponent: Tensor[Other]) -> Tensor[broadcast(_Shape, Other)]: ...
    @overload
    def pow(self, exponent: int | float) -> Self: ...
    @overload
    def __pow__[Other: IntTuple](self, other: Tensor[Other]) -> Tensor[broadcast(_Shape, Other)]: ...
    @overload
    def __pow__(self, other: int | float) -> Self: ...
    @overload
    def remainder[Other: IntTuple](self, other: Tensor[Other]) -> Tensor[broadcast(_Shape, Other)]: ...
    @overload
    def remainder(self, other: int | float) -> Self: ...
    def eq[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def ne[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def lt[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def le[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def gt[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def ge[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def logical_and[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def logical_or[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def atan2[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def hypot[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def fmod[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def copysign[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def nextafter[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def bitwise_and[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def bitwise_or[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def bitwise_xor[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def bitwise_left_shift[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def bitwise_right_shift[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def maximum[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def minimum[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def fmax[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def fmin[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def isclose[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, other: Tensor[Other], rtol: float = ..., atol: float = ..., equal_nan: bool = ...
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def lerp[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, end: Tensor[Other], weight: float
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    def masked_fill[Mask: IntTuple](  # pyrefly: ignore [bad-override]
        self, mask: Tensor[Mask], value: float
    ) -> Tensor[broadcast(_Shape, Mask)]: ...
    def masked_scatter[Mask: IntTuple](  # pyrefly: ignore [bad-override]
        self, mask: Tensor[Mask], source: Tensor
    ) -> Tensor[broadcast(_Shape, Mask)]: ...
    @overload
    def clamp_min[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, min: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    @overload
    def clamp_min(self, min: int | float) -> Tensor[_Shape]: ...
    @overload
    def clamp_max[Other: IntTuple](  # pyrefly: ignore [bad-override]
        self, max: Tensor[Other]
    ) -> Tensor[broadcast(_Shape, Other)]: ...
    @overload
    def clamp_max(self, max: int | float) -> Tensor[_Shape]: ...
    @overload
    def clamp[Min: IntTuple, Max: IntTuple](  # pyrefly: ignore [bad-override]
        self, min: Tensor[Min], max: Tensor[Max]
    ) -> Tensor[broadcast(broadcast(_Shape, Min), Max)]: ...
    @overload
    def clamp[Min: IntTuple](
        self, min: Tensor[Min], max: int | float | None = ...
    ) -> Tensor[broadcast(_Shape, Min)]: ...
    @overload
    def clamp[Max: IntTuple](self, min: int | float | None, max: Tensor[Max]) -> Tensor[broadcast(_Shape, Max)]: ...
    @overload
    def clamp[Max: IntTuple](self, *, max: Tensor[Max]) -> Tensor[broadcast(_Shape, Max)]: ...
    @overload
    def clamp(self, min: int | float | None = ..., max: int | float | None = ...) -> Tensor[_Shape]: ...
    @overload
    def clip[Min: IntTuple, Max: IntTuple](  # pyrefly: ignore [bad-override]
        self, min: Tensor[Min], max: Tensor[Max]
    ) -> Tensor[broadcast(broadcast(_Shape, Min), Max)]: ...
    @overload
    def clip[Min: IntTuple](
        self, min: Tensor[Min], max: int | float | None = ...
    ) -> Tensor[broadcast(_Shape, Min)]: ...
    @overload
    def clip[Max: IntTuple](self, min: int | float | None, max: Tensor[Max]) -> Tensor[broadcast(_Shape, Max)]: ...
    @overload
    def clip[Max: IntTuple](self, *, max: Tensor[Max]) -> Tensor[broadcast(_Shape, Max)]: ...
    @overload
    def clip(self, min: int | float | None = ..., max: int | float | None = ...) -> Tensor[_Shape]: ...

class SparseCOOTensor(_SparseTensor[_Shape], Generic[_Shape]): ...
class SparseCSRTensor(_SparseTensor[_Shape], Generic[_Shape]): ...
class SparseCSCTensor(_SparseTensor[_Shape], Generic[_Shape]): ...
class SparseBSRTensor(_SparseTensor[_Shape], Generic[_Shape]): ...
class SparseBSCTensor(_SparseTensor[_Shape], Generic[_Shape]): ...

SparseTensor = Union[SparseCOOTensor, SparseCSRTensor, SparseCSCTensor, SparseBSRTensor, SparseBSCTensor]

@overload
def require_sparse_coo(value: Tensor[_Shape]) -> SparseCOOTensor[_Shape]: ...
@overload
def require_sparse_coo(value: object) -> SparseCOOTensor: ...
@overload
def require_sparse_csr(value: Tensor[_Shape]) -> SparseCSRTensor[_Shape]: ...
@overload
def require_sparse_csr(value: object) -> SparseCSRTensor: ...
@overload
def require_sparse_csc(value: Tensor[_Shape]) -> SparseCSCTensor[_Shape]: ...
@overload
def require_sparse_csc(value: object) -> SparseCSCTensor: ...
@overload
def require_sparse_bsr(value: Tensor[_Shape]) -> SparseBSRTensor[_Shape]: ...
@overload
def require_sparse_bsr(value: object) -> SparseBSRTensor: ...
@overload
def require_sparse_bsc(value: Tensor[_Shape]) -> SparseBSCTensor[_Shape]: ...
@overload
def require_sparse_bsc(value: object) -> SparseBSCTensor: ...
@overload
def require_sparse_coo_or_csr(value: Tensor[_Shape]) -> SparseCOOTensor[_Shape] | SparseCSRTensor[_Shape]: ...
@overload
def require_sparse_coo_or_csr(value: object) -> SparseCOOTensor | SparseCSRTensor: ...
@overload
def require_sparse_coo_csr_or_csc(
    value: Tensor[_Shape],
) -> SparseCOOTensor[_Shape] | SparseCSRTensor[_Shape] | SparseCSCTensor[_Shape]: ...
@overload
def require_sparse_coo_csr_or_csc(value: object) -> SparseCOOTensor | SparseCSRTensor | SparseCSCTensor: ...
@overload
def is_sparse_coo(value: Tensor[_Shape]) -> TypeGuard[SparseCOOTensor[_Shape]]: ...
@overload
def is_sparse_coo(value: object) -> TypeGuard[SparseCOOTensor]: ...
@overload
def is_sparse_csr(value: Tensor[_Shape]) -> TypeGuard[SparseCSRTensor[_Shape]]: ...
@overload
def is_sparse_csr(value: object) -> TypeGuard[SparseCSRTensor]: ...
@overload
def is_sparse_csc(value: Tensor[_Shape]) -> TypeGuard[SparseCSCTensor[_Shape]]: ...
@overload
def is_sparse_csc(value: object) -> TypeGuard[SparseCSCTensor]: ...
@overload
def is_sparse_bsr(value: Tensor[_Shape]) -> TypeGuard[SparseBSRTensor[_Shape]]: ...
@overload
def is_sparse_bsr(value: object) -> TypeGuard[SparseBSRTensor]: ...
@overload
def is_sparse_bsc(value: Tensor[_Shape]) -> TypeGuard[SparseBSCTensor[_Shape]]: ...
@overload
def is_sparse_bsc(value: object) -> TypeGuard[SparseBSCTensor]: ...
