"""Optional shape-aware static view of the runtime NewType layout brands."""

from typing import Generic, TypeGuard, TypeVar, Union, overload

from shape_extensions import IntTuple
from torch import Tensor
from typing_extensions import Self

_Shape = TypeVar("_Shape", bound=IntTuple)

class _SparseTensor(Tensor[_Shape], Generic[_Shape]):
    # Like NewType at runtime, this constructor does not validate the layout.
    def __new__(cls, value: Tensor[_Shape]) -> Self: ...
    def clone(self, *, memory_format: object = ...) -> Self: ...
    def detach(self) -> Self: ...
    def to_dense(self, dtype: object = ..., *, masked_grad: bool = ...) -> Tensor[_Shape]: ...
    def to_sparse_coo(self) -> SparseCOOTensor[_Shape]: ...
    def to_sparse_csr(self, dense_dim: int | None = ...) -> SparseCSRTensor[_Shape]: ...
    def to_sparse_csc(self, dense_dim: int | None = ...) -> SparseCSCTensor[_Shape]: ...
    # Upstream annotates T as Self, which wrongly preserves compressed layout
    # and shape on transpose. Conservatively discard the layout and shape.
    @property
    def T(self) -> Tensor: ...  # pyrefly: ignore [bad-override]

class SparseCOOTensor(_SparseTensor[_Shape], Generic[_Shape]): ...
class SparseCSRTensor(_SparseTensor[_Shape], Generic[_Shape]): ...
class SparseCSCTensor(_SparseTensor[_Shape], Generic[_Shape]): ...
class SparseBSRTensor(_SparseTensor[_Shape], Generic[_Shape]): ...
class SparseBSCTensor(_SparseTensor[_Shape], Generic[_Shape]): ...

SparseTensor = Union[SparseCOOTensor, SparseCSRTensor, SparseCSCTensor, SparseBSRTensor, SparseBSCTensor]

@overload
def require_sparse_coo(value: Tensor[_Shape]) -> SparseCOOTensor[_Shape]: ...
@overload
def require_sparse_coo(value: object) -> SparseCOOTensor: ...
@overload
def require_sparse_csr(value: Tensor[_Shape]) -> SparseCSRTensor[_Shape]: ...
@overload
def require_sparse_csr(value: object) -> SparseCSRTensor: ...
@overload
def require_sparse_csc(value: Tensor[_Shape]) -> SparseCSCTensor[_Shape]: ...
@overload
def require_sparse_csc(value: object) -> SparseCSCTensor: ...
@overload
def require_sparse_bsr(value: Tensor[_Shape]) -> SparseBSRTensor[_Shape]: ...
@overload
def require_sparse_bsr(value: object) -> SparseBSRTensor: ...
@overload
def require_sparse_bsc(value: Tensor[_Shape]) -> SparseBSCTensor[_Shape]: ...
@overload
def require_sparse_bsc(value: object) -> SparseBSCTensor: ...
@overload
def require_sparse_coo_or_csr(value: Tensor[_Shape]) -> SparseCOOTensor[_Shape] | SparseCSRTensor[_Shape]: ...
@overload
def require_sparse_coo_or_csr(value: object) -> SparseCOOTensor | SparseCSRTensor: ...
@overload
def require_sparse_coo_csr_or_csc(
    value: Tensor[_Shape],
) -> SparseCOOTensor[_Shape] | SparseCSRTensor[_Shape] | SparseCSCTensor[_Shape]: ...
@overload
def require_sparse_coo_csr_or_csc(value: object) -> SparseCOOTensor | SparseCSRTensor | SparseCSCTensor: ...
@overload
def is_sparse_coo(value: Tensor[_Shape]) -> TypeGuard[SparseCOOTensor[_Shape]]: ...
@overload
def is_sparse_coo(value: object) -> TypeGuard[SparseCOOTensor]: ...
@overload
def is_sparse_csr(value: Tensor[_Shape]) -> TypeGuard[SparseCSRTensor[_Shape]]: ...
@overload
def is_sparse_csr(value: object) -> TypeGuard[SparseCSRTensor]: ...
@overload
def is_sparse_csc(value: Tensor[_Shape]) -> TypeGuard[SparseCSCTensor[_Shape]]: ...
@overload
def is_sparse_csc(value: object) -> TypeGuard[SparseCSCTensor]: ...
@overload
def is_sparse_bsr(value: Tensor[_Shape]) -> TypeGuard[SparseBSRTensor[_Shape]]: ...
@overload
def is_sparse_bsr(value: object) -> TypeGuard[SparseBSRTensor]: ...
@overload
def is_sparse_bsc(value: Tensor[_Shape]) -> TypeGuard[SparseBSCTensor[_Shape]]: ...
@overload
def is_sparse_bsc(value: object) -> TypeGuard[SparseBSCTensor]: ...
