# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.torch-type == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        torch-version: ["2.5.0", "2.13.0"]
        torch-type: ["stable"]
        include:
        - python-version: "3.12"
          torch-version: "nightly"
          torch-type: "nightly"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ "${{ matrix.torch-type }}" = "nightly" ]; then
          pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu
        else
          pip install torch==${{ matrix.torch-version }}
        fi
        pip install -r requirements-ci.txt
    - name: Lint check with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics
    - name: Check import sorting with isort
      run: |
        isort --check-only --diff .
    - name: Check code formatting with black
      run: |
        black --check .
    - name: Run pytest
      run: |
        python -m pytest --ignore=torchsparsegradutils/tests/test_doctests.py
    - name: Test installing package
      run: |
        python -m pip install .
